FROM python:3.6-alpine

COPY src/workq /opt/libs/
RUN pip install /opt/libs/workq

COPY src/cion_interface /opt/libs/
RUN pip install /opt/libs/cion_interface

WORKDIR /opt/worker

COPY src/worker/requirements.txt .
RUN pip install -r requirements.txt

COPY src/worker/worker.py .

CMD ["python", "worker.py"]