FROM python:3.6-alpine

COPY src/workq /opt/libs/workq
RUN pip install /opt/libs/workq

COPY src/cion_interface /opt/libs/cion_interface
RUN pip install /opt/libs/cion_interface

COPY src/async_rethink /opt/libs/async_rethink
RUN pip install /opt/libs/async_rethink

WORKDIR /opt/worker

COPY src/worker/requirements.txt .
RUN pip install -r requirements.txt

COPY src/worker/worker.py .
COPY src/worker/monkey_patch.py .
COPY src/worker/configuration configuration

CMD ["python", "worker.py"]